src/main/java/at/qe/sepm/skeleton/model/Holiday.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.qe.sepm.skeleton.model;

import org.springframework.data.domain.Persistable;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;

/**
 *
 * @author Manuel
 */
@Entity
public class Holiday implements Persistable<Date> {
    private static final long serialVersionUID = 1L;
    @Id
    private Date date;
    
    private String name;

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public Date getId() {
        return date;
    }

    @Override
    public boolean isNew() {
        return (date == null);
    }


}

src/main/java/at/qe/sepm/skeleton/model/LabDevice.java
package at.qe.sepm.skeleton.model;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;
import org.springframework.data.domain.Persistable;

import javax.persistence.*;
import java.util.List;

/**
 * Created by ${Marc} on ${05.12.2018}.
 */
@Entity
public class LabDevice implements Persistable<Integer> {


    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "device_id")
    private Integer id;

    @Column(nullable = false, unique = true)
    private String name;
    
    @ManyToOne(optional = true)
    private Laboratory laboratoryTag;
    @Column(nullable = false)
    private String deviceModel;
    @Column(nullable = false)
    private String location;
    private String annotation;
    @Column(nullable = false)
    private int maxDurationInHours;
    private boolean state;

    @Column
    @ManyToMany(mappedBy = "labDevices", cascade = CascadeType.ALL)
    @LazyCollection(LazyCollectionOption.FALSE)
    private List<LabDeviceGroup> labDeviceGroupTag;

    @OneToMany(orphanRemoval = true, cascade = {CascadeType.MERGE, CascadeType.REMOVE, CascadeType.REFRESH}, mappedBy = "labDeviceTag")
    @LazyCollection(LazyCollectionOption.FALSE)
    private List<Reservation> reservations;

    @OneToMany(orphanRemoval = true, cascade = {CascadeType.MERGE, CascadeType.REMOVE, CascadeType.REFRESH}, mappedBy = "labDeviceTag")
    @LazyCollection(LazyCollectionOption.FALSE)
    private List<LabDeviceFile> files;





    @Override
    public Integer getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return false;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Laboratory getLaboratory() {
        return laboratoryTag;
    }

    public void setLaboratory(Laboratory laboratoryTag) {
        this.laboratoryTag = laboratoryTag;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getAnnotation() {
        return annotation;
    }

    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }

    public int getMaxDurationInHours() {
        return maxDurationInHours;
    }
    
    public void setMaxDurationInHours(int maxDurationInHours) {
        this.maxDurationInHours = maxDurationInHours;
    }

    public boolean isState() {
        return state;
    }

    public void setState(boolean state) {
        this.state = state;
    }

    public List<Reservation> getReservations() {
        return reservations;
    }

    public void setReservations(List<Reservation> reservations) {
        this.reservations = reservations;
    }

    public String getDeviceModel() {
        return deviceModel;
    }

    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel;
    }

    public List<LabDeviceFile> getFiles() {
        return files;
    }

    public void setFiles(List<LabDeviceFile> files) {
        this.files = files;
    }


    public List<LabDeviceGroup> getLabDeviceGroupTag() {
        return labDeviceGroupTag;
    }

    public void setLabDeviceGroupTag(List<LabDeviceGroup> labDeviceGroupTag) {
        this.labDeviceGroupTag = labDeviceGroupTag;
    }
}

src/main/java/at/qe/sepm/skeleton/model/Reservation.java
package at.qe.sepm.skeleton.model;

import org.springframework.data.domain.Persistable;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;

/**
 * Created by ${Marc} on ${05.12.2018}.
 */

@Entity
public class Reservation implements Persistable<Integer> {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "res_id")
    private Integer id;
    @Column
    private LocalDate startDate;
    @Column
    private LocalDate endDate;
    @Column
    private LocalTime startTime;
    @Column
    private LocalTime endTime;
    @ManyToOne
    private User userTag;
    @ManyToOne
    private LabDevice labDeviceTag;

    private String annotation;

    @ManyToOne
    private LabDeviceGroup labDeviceGroup;

    @Column
    private String adminUsername;
    @Temporal(TemporalType.TIMESTAMP)
    private Date restitutionDate;
    
    private Boolean overdueMail;
    private Boolean remindMail;
   

    public String getAdminUsername() {
		return adminUsername;
	}

	public void setAdminUsername(String adminUsername) {
		this.adminUsername = adminUsername;
	}

	public Date getRestitutionDate() {
		return restitutionDate;
	}

	public void setRestitutionDate(Date restitutionDate) {
		this.restitutionDate = restitutionDate;
	}

	public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public LocalTime getStartTime() {
        return startTime;
    }

    public void setStartTime(LocalTime startTime) {
        this.startTime = startTime;
    }

    public LocalTime getEndTime() {
        return endTime;
    }

    public void setEndTime(LocalTime endTime) {
        this.endTime = endTime;
    }

    public User getUserTag() {
        return userTag;
    }

    public void setUserTag(User userId) {
        this.userTag = userId;
    }

    public LabDevice getLabDeviceTag() {
        return labDeviceTag;
    }

    public void setLabDeviceTag(LabDevice labDeviceTag) {
        this.labDeviceTag = labDeviceTag;
    }

    public Integer getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return false;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public LabDeviceGroup getLabDeviceGroup() {
        return labDeviceGroup;
    }

    public void setLabDeviceGroup(LabDeviceGroup labDeviceGroup) {
        this.labDeviceGroup = labDeviceGroup;
    }

    public String getAnnotation() {
        return annotation;
    }

    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }

    public Boolean getOverdueMail() {
        return overdueMail;
    }

    public void setOverdueMail(Boolean overdueMail) {
        this.overdueMail = overdueMail;
    }

    public Boolean getRemindMail() {
        return remindMail;
    }

    public void setRemindMail(Boolean remindMail) {
        this.remindMail = remindMail;
    }
}

src/main/java/at/qe/sepm/skeleton/ui/controllers/HolidayListController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.qe.sepm.skeleton.ui.controllers;

import at.qe.sepm.skeleton.model.Holiday;
import at.qe.sepm.skeleton.services.HolidayService;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author Manuel
 */
@Component
@Scope("view")
public class HolidayListController {
 
    @Autowired
    HolidayService holidayService;
    
    public List<Holiday> getHolidays(){
        return holidayService.getAllHolidays();
    }
}

src/main/java/at/qe/sepm/skeleton/ui/controllers/LabDeviceListController.java
package at.qe.sepm.skeleton.ui.controllers;

import at.qe.sepm.skeleton.model.LabDevice;
import at.qe.sepm.skeleton.services.LabDeviceService;
import at.qe.sepm.skeleton.services.ReservationService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

/**
 * Created by ${Marc} on ${05.12.2018}.
 */

@Component
@Scope("session")
public class LabDeviceListController implements Serializable {

    private static final long serialVersionUID = -7830965913689323493L;

    @Autowired
    private LabDeviceService labDeviceService;
    @Autowired
    private ReservationService reservationService;


    private String labDeviceModel;
    private LocalDate startDate;
    private Date tempStartDate;
    private LocalDate endDate;
    private Date tempEndDate;
    private LocalTime startTime;
    private Date tempStartTime;
    private LocalTime endTime;
    private Date tempEndTime;
    private List<LabDevice> filteredAllLabDevices;

    public List<LabDevice> getAllLabDevices() {
        return labDeviceService.getAllLabDevices();
    }

    public List<LabDevice> getAllLabDevicesByName(String name) {
        return labDeviceService.getLabDevicesAllByName(name);
    }

    public List<LabDevice> getAllLabDevicesOfLab(Integer labId) {return labDeviceService.getAllLabDevicesOfLab(labId); }

    public LabDevice getLabDeviceById(int id) {
        return labDeviceService.getLabDeviceById(id);
    }
    
    public void delete(LabDevice labDevice){
        labDeviceService.deleteLabDevice(labDevice);
    }

    private void setDateTimes() {
        startDate = tempStartDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        endDate = tempEndDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        startTime =tempStartTime.toInstant().atZone(ZoneId.systemDefault()).toLocalTime();
        endTime = tempEndTime.toInstant().atZone(ZoneId.systemDefault()).toLocalTime();
    }

    public List<LabDevice> getReservableLabDeviceOfModel() {
        setDateTimes();
        List<Integer> IDs = labDeviceService.getAllLabDeviceIds();
        List<LabDevice> labDevicesWithoutReservation = new LinkedList<>();
        for (int i = 0; i < IDs.size(); i++) {
            if (reservationService.getAllReservationsFromLabDeviceId(IDs.get(i)).isEmpty()) {
                labDevicesWithoutReservation.add(labDeviceService.getLabDeviceById(IDs.get(i)));
            }
        }
        labDevicesWithoutReservation.addAll(reservationService.getReservableLabDevicesOfModel(startDate, endDate, startTime, endTime, labDeviceModel));
        return labDevicesWithoutReservation;
    }

    public int getLabDeviceCount() {
        return labDeviceService.getAllLabDevices().size();
    }


    public String getLabDeviceModel() {
        return labDeviceModel;
    }

    public void setLabDeviceModel(String labDeviceModel) {
        this.labDeviceModel = labDeviceModel;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public Date getTempStartDate() {
        return tempStartDate;
    }

    public void setTempStartDate(Date tempStartDate) {
        this.tempStartDate = tempStartDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public Date getTempEndDate() {
        return tempEndDate;
    }

    public void setTempEndDate(Date tempEndDate) {
        this.tempEndDate = tempEndDate;
    }

    public LocalTime getStartTime() {
        return startTime;
    }

    public void setStartTime(LocalTime startTime) {
        this.startTime = startTime;
    }

    public Date getTempStartTime() {
        return tempStartTime;
    }

    public void setTempStartTime(Date tempStartTime) {
        this.tempStartTime = tempStartTime;
    }

    public LocalTime getEndTime() {
        return endTime;
    }

    public void setEndTime(LocalTime endTime) {
        this.endTime = endTime;
    }

    public Date getTempEndTime() {
        return tempEndTime;
    }

    public void setTempEndTime(Date tempEndTime) {
        this.tempEndTime = tempEndTime;
    }

	public List<LabDevice> getFilteredAllLabDevices() {
		return filteredAllLabDevices;
	}

	public void setFilteredAllLabDevices(List<LabDevice> filteredAllLabDevices) {
		this.filteredAllLabDevices = filteredAllLabDevices;
	}
}

src/main/java/at/qe/sepm/skeleton/ui/controllers/LaboratoryListController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.qe.sepm.skeleton.ui.controllers;

import at.qe.sepm.skeleton.model.Laboratory;
import at.qe.sepm.skeleton.services.LaboratoryService;
import java.io.Serializable;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author Manuel
 */
@Component
@Scope("view")
public class LaboratoryListController implements Serializable {
    
    @Autowired
    private LaboratoryService laboratoryService;

    public List<Laboratory> getAllLaboratories() {
        return laboratoryService.getAllLaboratories();
    }

    public List<Laboratory> getAllLaboratoriesByName(String name) {
        return laboratoryService.getAllLaborytorybyName(name);
    }
}

src/main/java/at/qe/sepm/skeleton/ui/controllers/RestitutionListController.java
/**
 * 
 */
package at.qe.sepm.skeleton.ui.controllers;

import java.io.Serializable;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import at.qe.sepm.skeleton.model.Reservation;
import at.qe.sepm.skeleton.model.UserRole;
import at.qe.sepm.skeleton.services.ReservationService;
import at.qe.sepm.skeleton.services.RestitutionService;
import at.qe.sepm.skeleton.ui.beans.SessionInfoBean;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;

/**
 * @author marco
 *
 */

@Component
@Scope("view")
public class RestitutionListController implements Serializable{

    @Autowired
    private RestitutionService restitutionService;
    
    @Autowired
    private ReservationService reservationService;
    
    @Autowired
    private SessionInfoBean sessionInfoBean;
    
    public List<Reservation> getAllRestitutions(){
        if(sessionInfoBean.getCurrentUser().getRoles().contains(UserRole.ADMIN)) return restitutionService.getAllActiveRestitutions();
        else return restitutionService.getAllActiveRestitutionsFromUsername(sessionInfoBean.getCurrentUserName());
    }
    
    public List<Reservation> getAllRestitutionsFromUsername(String username){
    	return restitutionService.getAllRestitutionsFromUsername(username);
    }
    
    public List<Reservation> getAllActiveReservations(){
		return reservationService.getAllActiveReservations();
    }
    
    public List<Reservation> getAllActiveReservationsFromUsername(String username){
    	return reservationService.getAllActiveReservationsFromUsername(username);
    }

    public boolean isRestitutionInStatus(Reservation reservation, String status){
        if(status.equals("DUE")){
            Date resEndDate = Date.from(LocalDateTime.of(reservation.getEndDate(), reservation.getEndTime()).atZone(ZoneId.of("CET")).toInstant());
            return (reservation.getRestitutionDate() == null && resEndDate.before(new Date()));
        }
        else if(status.equals("RUN")){
            Date resStartDate = Date.from(LocalDateTime.of(reservation.getStartDate(), reservation.getStartTime()).atZone(ZoneId.of("CET")).toInstant());
            Date resEndDate = Date.from(LocalDateTime.of(reservation.getEndDate(), reservation.getEndTime()).atZone(ZoneId.of("CET")).toInstant());
            Date aktDate = new Date();
            return (resStartDate.before(aktDate) && resEndDate.after(aktDate) && reservation.getRestitutionDate() == null);
        }
        else if(status.equals("DONE")){
            return reservation.getRestitutionDate() != null;
        }
        else return false;
    }
}

src/main/webapp/admin/labs.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
    <div class="content-wrapper">
    	<div class="box">
            <div class="box-header">
              <h3 class="box-title"><i class="fa fa-home"></i> Laborliste</h3>
            </div>
        <h:form id="labForm" class="templatewrapper">  
            <p:dataTable id="labsTable" var="lab" value="#{laboratoryListController.allLaboratories}">
                <p:column style="width:50px">
            		<p:rowToggler />
        		</p:column>
                <p:column headerText="ID" style="width:100px; text-align: center;">
                    <h:outputText value="#{lab.id}"/>
                </p:column>
                <p:column headerText="Name">
                    <h:outputText value="#{lab.laboratoryName}"/>
                </p:column>
                <p:column style="width:100px;text-align: center" rendered="#{sessionInfoBean.hasRole('ADMIN')}">
                    <p:commandButton  icon="fa fa-edit" title="Edit" class="btn btn-primary"  update=":labForm:labEditDialog" oncomplete="PF('labEditDialog').show()">
                        <f:setPropertyActionListener value="#{lab}" target="#{laboratoryOpeningTimeController.laboratory}" />
                    </p:commandButton>
                    <p:commandButton icon="fa fa-trash" title="Delete" class="btn btn-danger" update=":labForm:labsTable" action="#{laboratoryOpeningTimeController.doDeleteLaboratory}">
                        <f:setPropertyActionListener value="#{lab}" target="#{laboratoryOpeningTimeController.laboratory}" />
                        <p:confirm header="Achtung" message="Möchten Sie das ausgewählte Labor unwiderruflich löschen?" icon="ui-icon-alert" />
                    </p:commandButton>
                    
                </p:column>
                
                <p:rowExpansion>
		            <p:panelGrid  columns="2" columnClasses="ui-grid-col-6, ui-grid-col-2"  styleClass="panelNoBorder">
			            <p:panelGrid  columns="3" style="width:500px">
                    	<f:facet name="header">
                   			<h:outputText value="Öffnungszeiten" /> 
               			</f:facet>
                        <h:outputText value="Tag" />
                        <h:outputText value="von" />
                        <h:outputText value="bis" />
                        
                        <h:outputText value="Montag:" />
                        <h:outputText value="#{laboratoryOpeningTimeController.getOpeningTimeForLabrotoryAndDay(lab, 'MON').openTime}" ><f:convertDateTime timeZone="CET" pattern="HH:mm"/></h:outputText>
                        <h:outputText value="#{laboratoryOpeningTimeController.getOpeningTimeForLabrotoryAndDay(lab, 'MON').closeTime}" ><f:convertDateTime timeZone="CET" pattern="HH:mm"/></h:outputText>
                        
                        <h:outputText value="Dienstag:" />
                        <h:outputText value="#{laboratoryOpeningTimeController.getOpeningTimeForLabrotoryAndDay(lab, 'TUE').openTime}" ><f:convertDateTime timeZone="CET" pattern="HH:mm"/></h:outputText>
                        <h:outputText value="#{laboratoryOpeningTimeController.getOpeningTimeForLabrotoryAndDay(lab, 'TUE').closeTime}" ><f:convertDateTime timeZone="CET" pattern="HH:mm"/></h:outputText>
                        
                        <h:outputText value="Mittwoch:" />
                        <h:outputText value="#{laboratoryOpeningTimeController.getOpeningTimeForLabrotoryAndDay(lab, 'WED').openTime}" ><f:convertDateTime timeZone="CET" pattern="HH:mm"/></h:outputText>
                        <h:outputText value="#{laboratoryOpeningTimeController.getOpeningTimeForLabrotoryAndDay(lab, 'WED').closeTime}" ><f:convertDateTime timeZone="CET" pattern="HH:mm"/></h:outputText>
                        
                        <h:outputText value="Donnerstag:" />
                        <h:outputText value="#{laboratoryOpeningTimeController.getOpeningTimeForLabrotoryAndDay(lab, 'THU').openTime}" ><f:convertDateTime timeZone="CET" pattern="HH:mm"/></h:outputText>
                        <h:outputText value="#{laboratoryOpeningTimeController.getOpeningTimeForLabrotoryAndDay(lab, 'THU').closeTime}" ><f:convertDateTime timeZone="CET" pattern="HH:mm"/></h:outputText>
                        
                        <h:outputText value="Freitag:" />
                        <h:outputText value="#{laboratoryOpeningTimeController.getOpeningTimeForLabrotoryAndDay(lab, 'FRI').openTime}" ><f:convertDateTime timeZone="CET" pattern="HH:mm"/></h:outputText>
                        <h:outputText value="#{laboratoryOpeningTimeController.getOpeningTimeForLabrotoryAndDay(lab, 'FRI').closeTime}" ><f:convertDateTime timeZone="CET" pattern="HH:mm"/></h:outputText>
                        
                        <h:outputText value="Samstag:" />
                        <h:outputText value="geschlossen" />
                        <h:outputText value="geschlossen" />
                        
                        <h:outputText value="Sonntag:" />
                        <h:outputText value="geschlossen" />
                        <h:outputText value="geschlossen" />
                        
                    </p:panelGrid>

			            <p:panelGrid  columns="1">
							<p:commandButton icon="fa fa-flask" title="Show" value="Laborgeräte anzeigen" class="btn btn-primary" update=":labForm:labShowDialog" oncomplete="PF('labShowDialog').show()">
                        		<f:setPropertyActionListener value="#{lab}" target="#{labDeviceDetailController.lab}" />
                    		</p:commandButton>
	                    </p:panelGrid>
                    </p:panelGrid>

       			</p:rowExpansion>
               
            </p:dataTable>
            
            <!--  Edit Modal -->
            <p:dialog header="Öffnungszeiten ändern" id="labEditDialog" widgetVar="labEditDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">

                <p:panelGrid  columns="3" style="width:500px">
                    <f:facet name="header">
                            <h:outputText value="Öffnungszeiten" /> 
                    </f:facet>

                    <h:outputText value="Tag" />
                    <h:outputText value="von" />
                    <h:outputText value="bis" />

                    <h:outputText value="Montag:" />
                    <p:calendar id="monStart" value="#{laboratoryOpeningTimeController.mon.openTime}" timeOnly="true" pattern="HH:mm" maxHour="22" minHour="6" stepMinute="5" readonlyInput="true"/>  
                    <p:calendar id="monEnd" value="#{laboratoryOpeningTimeController.mon.closeTime}" timeOnly="true" pattern="HH:mm" maxHour="22" minHour="6" stepMinute="5" readonlyInput="true"/>

                    <h:outputText value="Dienstag:" />
                    <p:calendar id="tueStart" value="#{laboratoryOpeningTimeController.tue.openTime}" timeOnly="true" pattern="HH:mm" maxHour="22" minHour="6" stepMinute="5" readonlyInput="true"/>
                    <p:calendar id="tueEnd" value="#{laboratoryOpeningTimeController.tue.closeTime}" timeOnly="true" pattern="HH:mm" maxHour="22" minHour="6" stepMinute="5" readonlyInput="true"/>

                    <h:outputText value="Mittwoch:" />
                    <p:calendar id="wedStart" value="#{laboratoryOpeningTimeController.wed.openTime}" timeOnly="true" pattern="HH:mm" maxHour="22" minHour="6" stepMinute="5" readonlyInput="true"/>
                    <p:calendar id="wedEnd" value="#{laboratoryOpeningTimeController.wed.closeTime}" timeOnly="true" pattern="HH:mm" maxHour="22" minHour="6" stepMinute="5" readonlyInput="true"/>

                    <h:outputText value="Donnerstag:" />
                    <p:calendar id="thuStart" value="#{laboratoryOpeningTimeController.thu.openTime}" timeOnly="true" pattern="HH:mm" maxHour="22" minHour="6" stepMinute="5" readonlyInput="true"/>
                    <p:calendar id="thuEnd" value="#{laboratoryOpeningTimeController.thu.closeTime}" timeOnly="true" pattern="HH:mm" maxHour="22" minHour="6" stepMinute="5" readonlyInput="true"/>

                    <h:outputText value="Freitag" />
                    <p:calendar id="friStart" value="#{laboratoryOpeningTimeController.fri.openTime}" timeOnly="true" pattern="HH:mm" maxHour="22" minHour="6" stepMinute="5" readonlyInput="true"/>
                    <p:calendar id="friEnd" value="#{laboratoryOpeningTimeController.fri.closeTime}" timeOnly="true" pattern="HH:mm" maxHour="22" minHour="6" stepMinute="5" readonlyInput="true"/>

                    <h:outputText value="Samstag" />
                    <h:outputText value="geschlossen" />
                    <h:outputText value="geschlossen" />

                    <h:outputText value="Sonntag" />
                    <h:outputText value="geschlossen" />
                    <h:outputText value="geschlossen" />
                </p:panelGrid>
                <p:commandButton icon="fa fa-save" title="Save" value="Speichern" class="btn btn-primary" oncomplete="PF('labEditDialog').hide()" action="#{laboratoryOpeningTimeController.save}" style="margin-top: 10px;"/>
            </p:dialog>
            
            <!--  Show Devices Modal -->
            <p:dialog header="Geräte in diesem Labor" id="labShowDialog" widgetVar="labShowDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:dataTable value="#{labDeviceDetailController.allLabDevices}" var="device" style="width: 600px">
				            <p:column headerText="Gerätename">
                    			<h:outputText value="#{device.name}" style="font-weight: bold"/>
                			</p:column>
                			<p:column headerText="Standort">
                    			<h:outputText value="#{device.location}" style="font-weight: bold"/>
                			</p:column>
                			<p:column headerText="Zustand" style="text-align: center">
                    			<h:outputText class="label label-success" value="verfügbar" rendered="#{device.state}"/>
                    			<h:outputText class="label label-danger" value="gesperrt" rendered="#{!device.state}"/>
                			</p:column>
				        <hr />
				    </p:dataTable>
            </p:dialog>
            
            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" width="300">
                <p:commandButton value="Ja" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                <p:commandButton value="Nein" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
            </p:confirmDialog>
        </h:form>
        </div>
        </div>
    </ui:define>
</ui:composition>