src/main/java/at/qe/sepm/skeleton/ui/beans/SessionInfoBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.UserRole;
import at.qe.sepm.skeleton.services.UserService;
import java.io.IOException;
import javax.faces.context.FacesContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

/**
 * Session information bean to retrieve session-specific parameters.
 *
 * This class is part of the skeleton project provided for students of the
 * course "Softwaredevelopment and Project Management" offered by the University
 * of Innsbruck.
 */
@Component
@Scope("session")
public class SessionInfoBean {

    @Autowired
    private UserService userService;

    /**
     * Attribute to cache the current user.
     */
    private User currentUser;

    /**
     * Returns the currently logged on user, null if no user is authenticated
     * for this session.
     *
     * @return
     */
    public User getCurrentUser() {
        if (currentUser == null) {
            String currentUserName = getCurrentUserName();
            if (currentUserName.isEmpty()) {
                return null;
            }
            currentUser = userService.loadUser(currentUserName);
        }
        return currentUser;
    }
    
    public String getCurrentUserInfo(){
        if (!isLoggedIn()) {
            return "";
        }
        User user = getCurrentUser();
        if(user != null) return user.getFirstName() + " " + user.getLastName();
        else return "";
    }

    /**
     * Returns the username of the user for this session, empty string if no
     * user has been authenticated for this session.
     *
     * @return
     */
    public String getCurrentUserName() {
        if (!isLoggedIn()) {
            return "";
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String name = auth.getName(); //get logged in username
        return name;
    }

    /**
     * Returns the roles of the user for this session as space-separated list,
     * empty string if no user has been authenticated for this session-
     *
     * @return
     */
    public String getCurrentUserRoles() {
        if (!isLoggedIn()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority role : auth.getAuthorities()) {
            sb.append(role.getAuthority());
            sb.append(' ');
        }
        return sb.toString().trim();
    }

    /**
     * Checks if a user is authenticated for this session.
     *
     * @return true if a non-anonymous user has been authenticated, false
     * otherwise
     */
    public boolean isLoggedIn() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null) {
            return auth.isAuthenticated() && !auth.getName().equals("anonymousUser");
        } else {
            return false;
        }
    }

    /**
     * Checks if the user for this session has the given role (c.f.
     * {@link UserRole}).
     *
     * @param role the role to check for as string
     * @return true if a user is authenticated and the current user has the
     * given role, false otherwise
     */
    public boolean hasRole(String role) {
        if (role == null || role.isEmpty() || !isLoggedIn()) {
            return false;
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority ga : auth.getAuthorities()) {
            if (role.equals(ga.getAuthority())) {
                return true;
            }
        }
        return false;
    }

}

src/main/webapp/WEB-INF/includes/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <body>
        <ui:composition>

        

        </ui:composition>
    </body>
</html>

src/main/webapp/WEB-INF/includes/header.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <body>
        <ui:composition>
        
    <header class="main-header">

    <a href="../../secured/welcome.xhtml" class="logo">
      
      <span class="logo-mini"><b>UIBK Geräte</b></span>

      <span class="logo-lg"><b>UIBK Geräte</b></span>
    </a>


    <nav class="navbar navbar-static-top">

      <h:panelGroup rendered="#{sessionInfoBean.loggedIn}">
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Menü einklappen</span>
      </a>
      </h:panelGroup>
      

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
        <h:panelGroup rendered="#{sessionInfoBean.loggedIn}">

          
          
          
          </h:panelGroup>
          <ui:fragment rendered="#{sessionInfoBean.loggedIn}">
          <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-danger"><h:outputText rendered="#{countController.countDueReservations!=0}" value="#{countController.countDueReservations}"/></span>
            </a>
            <ul class="dropdown-menu">
              
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  
                  <li>
                    <a href="../admin/restitution.xhtml">
                    <ui:fragment rendered="#{countController.countDueReservations>1}">
                      <i class="fa fa-warning text-red"></i> <b> #{countController.countDueReservations} Rückgaben überfällig!</b>
                      </ui:fragment>
                      <ui:fragment rendered="#{countController.countDueReservations==1}">
                      <i class="fa fa-warning text-red"></i> <b> #{countController.countDueReservations} Rückgabe überfällig!</b>
                      </ui:fragment>
                      <ui:fragment rendered="#{countController.countDueReservations==0}">
                      <b>keine Neuigkeiten</b>
                      </ui:fragment>
                    </a>
                  </li>
                 
                </ul>
              </li>
              <ui:fragment rendered="#{countController.countDueReservations!=0}">
              <li class="footer"><a href="../admin/restitution.xhtml">mehr</a></li>
              </ui:fragment>
            </ul>
          </li>
          </ui:fragment>
          
          <li class="dropdown user user-menu" style="padding-bottom: 10px;">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             <div style="float: right; font-weight: bold">
                <ui:fragment rendered="#{sessionInfoBean.loggedIn}">
                    eingeloggt als #{sessionInfoBean.currentUserInfo}
                </ui:fragment>
                <ui:fragment rendered="#{!sessionInfoBean.loggedIn}">
                    nicht eingeloggt
                </ui:fragment>
            </div>
            </a>
            <ul class="dropdown-menu">
              
              
              <li class="user-footer">
                
                <div class="row">
		        <div class="col-xs-12">
		        	<form method="get" action="/logout">
		        		<button type="submit" class="btn btn-primary btn-block btn-flat" >Abmelden</button>
		        	</form>
		    
		        </div>
		      </div>
              </li>
            </ul>
          </li>
          
        </ul>
      </div>
	
    </nav>
  </header>
  <h:panelGroup rendered="#{sessionInfoBean.loggedIn}">
  <aside class="main-sidebar">
    
    <section class="sidebar" style="height: auto;">
      
      
      
      <div class="sidemenu">
      <ul class="sidebar-menu tree" data-widget="tree">
        <li class="header">Hauptmenü</li>
         <li>
            <a href="../../secured/welcome.xhtml" ><i class="fa fa-Dashboard"></i> <span>Übersicht</span>
            	<!-- 
            	 <span class="pull-right-container">
              <small class="label pull-right bg-yellow">12</small>
              <small class="label pull-right bg-green">16</small>
              <small class="label pull-right bg-red">5</small>
            </span>
             -->
            </a>
         </li>
         
         <li class="treeview">
          <a href="#">
            <i class="fa fa-home" aria-hidden="true"></i>
            <span>Labore</span>
            <span class="pull-right-container">
            	
              <i class="fa fa-angle-left pull-right"></i>
              
            </span>
          </a>
          <ul class="treeview-menu">
            <li><p:button href="../admin/labs.xhtml" value="Laborliste" icon="fa fa-list" class="menubutton"/></li>
            <li>
            <h:form>
            	  <p:commandButton icon="fa fa-plus-square" title="neues Labor" rendered="#{sessionInfoBean.hasRole('ADMIN')}" value="neues Labor" update=":addForm:labNewDialog" oncomplete="PF('labNewDialog').show()" class="menubutton"/>
   			</h:form>
            </li>
          </ul>
        </li>
       
         <li class="treeview">
          <a href="#">
            <i class="fa fa-flask" aria-hidden="true"></i>
            <span>Laborgeräte</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
              
            </span>
          </a>
          <ul class="treeview-menu">
            <li><p:button href="../admin/labdevices.xhtml" value="Geräteliste" icon="fa fa-list" class="menubutton" /></li>
            <li>
            <h:form>
            	<p:commandButton icon="fa fa-plus-square" rendered="#{sessionInfoBean.hasRole('ADMIN')}" title="neues Gerät" value="neues Gerät" update=":addForm:deviceNewDialog" oncomplete="PF('deviceNewDialog').show()" action="#{labDeviceDetailController.createNew}" class="menubutton"/>
   			</h:form></li>
          </ul>
        </li>
        
        <h:panelGroup rendered="#{sessionInfoBean.hasRole('ADMIN') or sessionInfoBean.hasRole('EMPLOYEE')}">
        <li class="treeview">
          <a href="#">
            <i class="fa fa-object-group" aria-hidden="true"></i>
            <span>Gerätegruppen</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><p:button href="../admin/devicegroups.xhtml" value="Gruppenliste" icon="fa fa-list" class="menubutton" /></li>
            <li>
            <h:form>
            	<p:commandButton icon="fa fa-plus-square" title="neue Gerätegruppe" value="neue Gerätegruppe" update=":addForm:groupNewDialog" oncomplete="PF('groupNewDialog').show()" action="#{labDeviceGroupDetailController.createNewLabDeviceGroup}" class="menubutton"/>
   			</h:form></li>
          </ul>
        </li>
        </h:panelGroup>
         
        <li class="treeview">
          <a href="#">
            <i class="fa fa-book" aria-hidden="true"></i>
            <span>Reservierungen</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
              <small class="label pull-right bg-blue"><h:outputText rendered="#{countController.countOpenReservations>0}" value="#{countController.countOpenReservations}" /></small>
              <small class="label pull-right bg-yellow"><h:outputText rendered="#{countController.countRunReservations>0}" value="#{countController.countRunReservations}" /></small>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><p:button href="../admin/reservations.xhtml" value="Reservierungsliste" icon="fa fa-list" class="menubutton"/></li>
            <h:form>
                <p:commandButton icon="fa fa-check-square" title="neue Reservierung" value="neue Reservierung" update=":addForm:reservationNewDialog" oncomplete="PF('reservationNewDialog').show()" class="menubutton" action="#{newReservationController.initMultiselectReservation()}"/>
   			</h:form>
          </ul>
        </li>
        
        <li class="treeview">
          <a href="#">
            <i class="fa fa-undo" aria-hidden="true"></i>
            <span>Rückgaben</span>
            
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
              <small class="label pull-right bg-red"><h:outputText rendered="#{countController.countDueReservations>0}" value="#{countController.countDueReservations}" /></small>
              <small class="label pull-right bg-green"><h:outputText rendered="#{countController.countDoneReservations>0}" value="#{countController.countDoneReservations}" /></small>
            </span>
          </a>
          <ul class="treeview-menu">

            <li><a href="../admin/restitution.xhtml"><i class="fa fa-list" aria-hidden="true"></i> Rückgabenliste</a></li>
          </ul>
        </li>

		<h:panelGroup rendered="#{sessionInfoBean.hasRole('ADMIN')}">
        <li class="treeview">
          <a href="../admin/users.xhtml">
            <i class="fa fa-users"></i> <span>Benutzerverwaltung</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><p:button href="../admin/users.xhtml" value="Benutzerliste" icon="fa fa-list" class="menubutton"/></li>
           
            <li>
            <h:form>
            	<p:commandButton icon="fa fa-user-plus" title="neuer Benutzer" value="neuer Benutzer" update=":addForm:userNewDialog" oncomplete="PF('userNewDialog').show()" class="menubutton"/>
   			</h:form>
            </li>
            
          </ul>
        </li>
       </h:panelGroup>
       
       <h:panelGroup rendered="#{sessionInfoBean.hasRole('ADMIN')}">
          <li class="treeview">
          <a href="">
            <i class="fa fa-gear"></i> <span>Einstellungen</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
            <ul class="treeview-menu">
            <li><p:button href="../admin/holiday.xhtml" value="Feiertage" icon="fa fa-calendar-times-o" class="menubutton"/></li>
            <li>
            <h:form>
            	<p:commandButton icon="fa fa-envelope" title="Mailserver" value="Mailserver" update=":addForm:mailEditDialog" oncomplete="PF('mailEditDialog').show()" class="menubutton" action="#{settingController.loadSettings}"/>
   			</h:form>
            </li>
          </ul>
          </li>
        </h:panelGroup>
          
     </ul>
     </div>
    </section>
  </aside>
  
  
  		</h:panelGroup>
  		
  		<!-- includes all Create Modals for Menü -->
  		<ui:include src="addModals.xhtml"/>
        </ui:composition>
    </body>
</html>